src/Entity/Reasons.php
<?php

namespace App\Entity;

use App\Controller\ProfileController;
use App\Controller\TimeController;
use DateTime;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ReasonRepository")
 */
class Reasons
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Reason;

    /**
     * @ORM\Column(type="integer")
     */
    private $Time;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Type;

    /**
     * @ORM\Column(type="datetime")
     */
    private $Added_at;

    /**
     * @ORM\Column(type="integer")
     */
    private $Bans;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Perms;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReason(): ?string
    {
        return $this->Reason;
    }

    public function setReason(string $Reason): self
    {
        $this->Reason = $Reason;

        return $this;
    }

    public function getTime(): ?int
    {
        return $this->Time;
    }

    public function setTime(int $Time): self
    {
        $this->Time = $Time;

        return $this;
    }

    public function getType(): ?bool
    {
        return $this->Type;
    }

    public function setType(bool $Type): self
    {
        $this->Type = $Type;

        return $this;
    }

    public function getAddedAt(): ?\DateTimeInterface
    {
        return $this->Added_at;
    }

    public function setAddedAt(\DateTimeInterface $Added_at): self
    {
        $this->Added_at = $Added_at;

        return $this;
    }

    public function getBans(): ?int
    {
        return $this->Bans;
    }

    public function setBans(int $Bans): self
    {
        $this->Bans = $Bans;

        return $this;
    }

    public function getPerms(): ?string
    {
        return $this->Perms;
    }

    public function setPerms(?string $Perms): self
    {
        $this->Perms = $Perms;

        return $this;
    }

    public function getFormattedTime($day, $days, $hour, $hours, $minute, $minutes)
    {
        $time = $this->getTime() * 60;

        $timePunish = new DateTime();
        $timePunish->setTimestamp(time() - $time);
        $now = new DateTime();
        $diff = $now->diff($timePunish, true);

        $timeStr = "";
        if($diff->days != 0){
            $timeStr .= $this->buildTimeSnippet($diff->days, $day, $days);
        } else {
            if($diff->h != 0){
                $timeStr .= $this->buildTimeSnippet($diff->h, $hour, $hours);
            }
            if($diff->i != 0){
                $timeStr .= $this->buildTimeSnippet($diff->i, $minute, $minutes);
            }
        }

        return $timeStr;
    }

    private function buildTimeSnippet($number, $singular, $plural){
        if(is_numeric($number)){
            return ($number == 1) ? $number . " " . $singular . " " : $number . " " . $plural . " ";
        }
    }

    /*
     * Dummy function for form
     */
    private $UnitType;

    public function getUnitType(){
        if($this->getTime() != -1){
            return 0;
        } else {
            return 3;
        }
    }

    public function getRealUnitType(){
        return $this->UnitType;
    }

    public function setUnitType($type){
        $this->UnitType = $type;
    }
}

src/Form/ReasonType.php
<?php

namespace App\Form;

use App\Entity\Reasons;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReasonType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Reason', TextType::class, [
                'attr' => [
                    'class' => "form-control"
                ],
                'label' => 'reason'
            ])
            ->add('Time', IntegerType::class, [
                'attr' => [
                    'class' => "form-control",
                    'id' => 'unit',
                    'style' => 'display: block;'
                ],
                'required' => false,
                'label' => 'duration'
            ])
            ->add('UnitType', ChoiceType::class, [
                'choices' => [
                    'minutes' => 0,
                    'hours' => 1,
                    'days' => 2,
                    'Permanent' => 3
                ],
                'attr' => [
                    'class' => "form-control",
                    'onchange' => 'toggleUnitField()'
                ],
                'label' => 'unittype'
            ])
            ->add('Type', ChoiceType::class, [
                'choices' => [
                    'Ban' => 0,
                    'Mute' => 1
                ],
                'attr' => [
                    'class' => "form-control"
                ],
                'label' => 'type'
            ])
            ->add('Perms', TextType::class, [
                'attr' => [
                    'class' => "form-control"
                ],
                'label' => 'Permissions',
                'required' => false
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'save',
                'attr' => [
                    'class' => 'btn btn-primary'
                ]
            ])
        ;
    }
}

src/Controller/Api/ReasonsController.php
<?php

namespace App\Controller\Api;

use App\Entity\Privatemessages;
use App\Repository\BansRepository;
use App\Repository\PrivatemessageRepository;
use App\Repository\ReasonRepository;
use App\Repository\TokensRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ReasonsController extends AbstractController{

    private $tokensRepository;
    private $reasonRepository;

    public function __construct(TokensRepository $tokensRepository, ReasonRepository $reasonRepository)
    {
        $this->tokensRepository = $tokensRepository;
        $this->reasonRepository = $reasonRepository;
    }

    /**
     * @Route("/api/reasons/delete", name="api.reasons.delete", methods={"POST"})
     */
    public function index(Request $request){
        $request = json_decode($request->getContent());
        $token = $this->tokensRepository->findOneBy(['token' => (array_key_exists("token", $request)) ? $request->token : null]);
        if(!$token){
            return $this->json([
                'error' => 'Not permitted'
            ], 401);
        }

        if(array_key_exists("reason", $request)){
            $reason = $this->reasonRepository->findOneBy(['id' => $request->reason]);
            if(!$reason){
                return $this->json([
                    'error' => 'Reason not found',
                ], 404);
            }

            $em = $this->getDoctrine()->getManager();
            $em->remove($reason);
            $em->flush();

            return $this->json([
                'success' => 'Reason deleted',
            ]);
        } else {
            return $this->json([
                'error' => 'Invalid request',
            ], 400);
        }
    }

}

src/Controller/ReasonController.php
<?php

namespace App\Controller;

use App\Entity\Reasons;
use App\Form\EditReasonType;
use App\Form\ReasonType;
use App\Repository\ReasonRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * @Route("/reasons", name="reason.")
 */
class ReasonController extends AbstractController
{

    private $reasonRepository;
    private $paginator;
    private $translator;

    public function __construct(ReasonRepository $reasonRepository, PaginatorInterface $paginator, TranslatorInterface $translator)
    {
        $this->reasonRepository = $reasonRepository;
        $this->paginator = $paginator;
        $this->translator = $translator;
    }

    /**
     * @Route("/", name="index")
     */
    public function index(Request $request)
    {
        $reasons = $this->reasonRepository->findAll();

        $page_reasons = $this->paginator->paginate(
            $reasons,
            $request->query->getInt('page', 1), /*page number*/
            10
        );

        return $this->render('reason/index.html.twig', [
            'reasons' => $page_reasons
        ]);
    }

    /**
     * @Route("/add", name="add")
     */
    public function add(Request $request){
        $form = $this->createForm(ReasonType::class);

        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $reason = new Reasons();

            $reason->setReason($form->get('Reason')->getData());

            $time = (int) $form->get('Time')->getData();
            $type = (int) $form->get('UnitType')->getData();

            if($time == 0 && $type != 3){
                $this->addFlash('error', $this->translator->trans('err_time'));
            } else {
                switch ($type){
                    case 1:
                        //Hours
                        $time = $time * 60;
                        break;
                    case 2:
                        //Days
                        $time = $time * 24 * 60;
                        break;
                    case 3:
                        //Permanent
                        $time = -1;
                        break;
                }

                $reason->setTime($time);

                $reason->setType($form->get('Type')->getData());
                $reason->setPerms($form->get('Perms')->getData());


                $reason->setAddedAt(new \DateTime());
                $reason->setBans(0);

                $em = $this->getDoctrine()->getManager();
                $em->persist($reason);
                $em->flush();

                $this->addFlash('success', $this->translator->trans('success_added'));
                return $this->redirectToRoute('reason.index');
            }
        }

        return $this->render('reason/add.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/delete/{id}", name="delete")
     */
    public function delete($id){
        $reason = $this->reasonRepository->findOneBy(['id' => $id]);

        $em = $this->getDoctrine()->getManager();

        if($reason){
            $em->remove($reason);
            $em->flush();

            $this->addFlash('success', 'Reason #'.$id.' was successfully deleted.');
        } else {
            $this->addFlash('error', 'Reason not found');
        }

        return $this->redirectToRoute('reason.index');
    }

    /**
     * @Route("/edit/{id}", name="edit")
     */
    public function edit($id, Request $request){
        $reason = $this->reasonRepository->findOneBy(['id' => $id]);

        $form = $this->createForm(ReasonType::class, $reason);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $time = $reason->getTime();
            switch ($reason->getRealUnitType()){
                case 1:
                    //Hours
                    $time = $time * 60;
                    break;
                case 2:
                    //Days
                    $time = $time * 24 * 60;
                    break;
                case 3:
                    //Permanent
                    $time = -1;
                    break;
            }
            $reason->setTime($time);

            $em = $this->getDoctrine()->getManager();
            $em->flush();
            return $this->redirectToRoute('reason.index');
        }

        if(!$reason){
            $this->addFlash('error', 'Reason not found');
            return $this->redirectToRoute('reason.index');
        }

        return $this->render('reason/edit.html.twig', [
            'reason' => $reason,
            'form' => $form->createView()
        ]);
    }
}

templates/reason/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bans{% endblock %}

{% block body %}
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>{{ 'add_reason'|trans }}</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ path('home.index') }}">Home</a></li>
                            <li class="breadcrumb-item">{{ 'nav_reasons'|trans }}</li>
                            <li class="breadcrumb-item active">{{ 'add_reason'|trans }}</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        {% include 'messages.html.twig' %}

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <!-- /.card-header -->
                        <div class="card-body">
                            {{ form(form) }}
                        </div>
                        <script>
                            function toggleUnitField(){
                                var unitfield = document.getElementById('reason_Time');
                                var choice = document.getElementById('reason_UnitType');

                                console.log(choice.selectedIndex);

                                if(choice.selectedIndex == 3){
                                    unitfield.style.display = "none";
                                } else {
                                    unitfield.style.display = "block";
                                }
                            }
                        </script>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
{% endblock %}

templates/reason/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit reason{% endblock %}

{% block body %}
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>{{ 'edit_reason'|trans }}</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ path('home.index') }}">Home</a></li>
                            <li class="breadcrumb-item active">Reasons</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        {% include 'messages.html.twig' %}

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <!-- /.card-header -->
                        <div class="card-body">
                            {{ form(form) }}
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
{% endblock %}

templates/reason/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reasons{% endblock %}

{% block body %}
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>{{ 'nav_reasons'|trans }}</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ path('home.index') }}">Home</a></li>
                            <li class="breadcrumb-item active">{{ 'nav_reasons'|trans }}</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        {% include 'messages.html.twig' %}

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <a class="btn btn-success btn-sm" href="{{ path('reason.add') }}">
                                <i class="fas fa-plus">
                                </i>
                                {{ 'create'|trans }}
                            </a>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>{{ 'reason'|trans }}</th>
                                    <th>{{ 'duration'|trans }}</th>
                                    <th>{{ 'reasontype'|trans }}</th>
                                    <th>{{ 'added_at'|trans }}</th>
                                    <th>{{ 'uses'|trans }}</th>
                                    <th>Permission</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for reason in reasons %}
                                    <tr>
                                        <td>{{ reason.id}}</td>
                                        <td>{{ reason.reason }}</td>
                                        <td>{{ reason.FormattedTime('day'|trans, 'days'|trans, 'hour'|trans, 'hours'|trans, 'minute'|trans, 'minutes'|trans) }}</td>
                                        <td>
                                            {% if reason.type == 0 %}
                                                Ban
                                            {% else %}
                                                Mute
                                            {% endif %}
                                        </td>
                                        <td>{{ reason.addedat|format_datetime(locale="de") }}</td>
                                        <td>{{ reason.bans }}</td>
                                        <td>
                                            {% if reason.perms == null %}
                                                -
                                            {% else %}
                                                {{ reason.perms }}
                                            {% endif %}
                                        </td>
                                        <td>
                                            <a class="btn btn-warning btn-sm" href="{{ path('reason.edit', {'id': reason.id}) }}">
                                                <i class="fas fa-edit"></i>
                                                {{ 'edit'|trans }}
                                            </a>
                                            <a class="btn btn-danger btn-sm" href="{{ path('reason.delete', {'id': reason.id}) }}">
                                                <i class="fas fa-trash">
                                                </i>
                                                {{ 'delete'|trans }}
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>{{ 'reason'|trans }}</th>
                                    <th>{{ 'duration'|trans }}</th>
                                    <th>{{ 'reasontype'|trans }}</th>
                                    <th>{{ 'added_at'|trans }}</th>
                                    <th>{{ 'uses'|trans }}</th>
                                    <th>Permission</th>
                                    <th>Action</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                        <div class="navigation">
                            {{ knp_pagination_render(reasons) }}
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
{% endblock %}