src/Entity/Bans.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="BansRepository")
 */
class Bans
{

    /**
     * @ORM\Id
     * @ORM\Column(type="string", length=255)
     */
    private $UUID;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="integer")
     */
    private $Banned;

    /**
     * @ORM\Column(type="integer")
     */
    private $Muted;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Reason;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $End;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Teamuuid;

    /**
     * @ORM\Column(type="integer")
     */
    private $Bans;

    /**
     * @ORM\Column(type="integer")
     */
    private $Mutes;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Firstlogin;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Lastlogin;

    /**
     * @ORM\Column(type="integer")
     */
    private $OnlineStatus;

    /**
     * @ORM\Column(type="integer")
     */
    private $OnlineTime;

    public function getUUID(): ?string
    {
        return $this->UUID;
    }

    public function setUUID(string $UUID): self
    {
        $this->UUID = $UUID;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getBanned(): ?int
    {
        return $this->Banned;
    }

    public function setBanned(int $Banned): self
    {
        $this->Banned = $Banned;

        return $this;
    }

    public function getMuted(): ?int
    {
        return $this->Muted;
    }

    public function setMuted(int $Muted): self
    {
        $this->Muted = $Muted;

        return $this;
    }

    public function getReason(): ?string
    {
        return $this->Reason;
    }

    public function setReason(string $Reason): self
    {
        $this->Reason = $Reason;

        return $this;
    }

    public function getEnd(): ?string
    {
        return $this->End;
    }

    public function setEnd(int $End): self
    {
        $this->End = $End;

        return $this;
    }

    public function getTeamUUID(): ?string
    {
        return $this->Teamuuid;
    }

    public function setTeamUUID(string $TeamUUID): self
    {
        $this->Teamuuid = $TeamUUID;

        return $this;
    }

    public function getBans(): ?int
    {
        return $this->Bans;
    }

    public function setBans(int $Bans): self
    {
        $this->Bans = $Bans;

        return $this;
    }

    public function getMutes(): ?int
    {
        return $this->Mutes;
    }

    public function setMutes(int $Mutes): self
    {
        $this->Mutes = $Mutes;

        return $this;
    }

    public function getFirstlogin(): ?string
    {
        return $this->Firstlogin;
    }

    public function setFirstlogin(string $Firstlogin): self
    {
        $this->Firstlogin = $Firstlogin;

        return $this;
    }

    public function getLastlogin(): ?string
    {
        return $this->Lastlogin;
    }

    public function setLastlogin(string $Lastlogin): self
    {
        $this->Lastlogin = $Lastlogin;

        return $this;
    }

    public function getOnlinestatus(): ?int
    {
        return $this->OnlineStatus;
    }

    public function setOnlinestatus(int $Onlinestatus): self
    {
        $this->OnlineStatus = $Onlinestatus;

        return $this;
    }

    public function getOnlinetime(): ?int
    {
        return $this->OnlineTime;
    }

    public function setOnlinetime(int $Onlinetime): self
    {
        $this->OnlineTime = $Onlinetime;

        return $this;
    }

    public function getFormattedEnd(){
        if($this->End != null && $this->End != "null"){
            $phpTimestamp = round($this->End / 1000);
            return $phpTimestamp;
        }
    }
}

src/Form/BanType.php
<?php

namespace App\Form;

use App\Entity\Reasons;
use App\Repository\ReasonRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class BanType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Name', TextType::class, [
                'attr' => [
                    'class' => "form-control"
                ],
                'label' => 'player'
            ])
            ->add('Reason', EntityType::class, [
                'class' => Reasons::class,
                'choice_label' => 'reason',
                'attr' => [
                    'class' => 'form-control'
                ],
                'query_builder' => function (ReasonRepository $er) {
                    return $er->createQueryBuilder('r')
                        ->where('r.Type = 0');
                },
                'label' => 'reason'
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'Ban',
                'attr' => [
                    'class' => 'btn btn-primary'
                ]
            ])
        ;
    }

}

src/Controller/BanController.php
<?php

namespace App\Controller;

use App\Form\BanType;
use App\Repository\BansRepository;
use App\Repository\ReasonRepository;
use App\Repository\UserRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/bans", name="ban.")
 */
class BanController extends AbstractController
{

    private $bansRepository;
    private $reasonRepository;
    private $userRepository;
    private $paginator;

    public function __construct(BansRepository $bansRepository, ReasonRepository $reasonRepository, UserRepository $userRepository, PaginatorInterface $paginator)
    {
        $this->bansRepository = $bansRepository;
        $this->reasonRepository = $reasonRepository;
        $this->userRepository = $userRepository;
        $this->paginator = $paginator;
    }

    /**
     * @Route("/", name="index")
     */
    public function index(Request $request)
    {
        $bans = $this->bansRepository->findBy(["Banned" => 1]);

        foreach ($bans as $ban){
            $punisherBan = $this->bansRepository->findOneBy(["UUID" => $ban->getTeamUUID()]);
            $ban->setTeamUUID($punisherBan->getName());
        }

        $bans_page = $this->paginator->paginate(
            $bans,
            $request->query->getInt('page', 1), /*page number*/
            10
        );

        return $this->render('ban/index.html.twig', [
            'bans' => $bans_page
        ]);
    }

    /**
     * @Route("/ban", name="ban")
     */
    public function ban(Request $request){
        $form = $this->createForm(BanType::class);

        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $ban = $this->bansRepository->findOneBy(["Name" => $form->get('Name')->getData()]);
            $authedUser = $this->userRepository->findOneBy(["username" => $this->getUser()->getUsername()]);
            $reason = $form->get('Reason')->getData();

            if($ban){
                if($ban->getBanned() == 0){
                    /*
                * Calc when ban ends
                */
                    if($reason->getTime() != -1){
                        $banTime = $reason->getTime() * 60 * 1000;
                        $now = time() * 1000;
                        $endTime = $now + $banTime;
                    } else {
                        $endTime = -1;
                    }

                    $ban->setBanned(1);
                    $ban->setReason($reason->getReason());
                    $ban->setEnd($endTime);
                    $ban->setTeamUUID($authedUser->getUuid());

                    $em = $this->getDoctrine()->getManager();
                    $em->persist($ban);
                    $em->flush();

                    return $this->redirectToRoute("ban.index");
                } else {
                    $this->addFlash("error", "This player is already banned");
                }
            } else {
                $this->addFlash("error", "This player could not found");
            }
        }

        return $this->render('ban/ban.html.twig', [
            "form" => $form->createView()
        ]);
    }

    /**
     * @Route("/unban/{name}", name="unban")
     */
    public function unban($name){
        $ban = $this->bansRepository->findOneBy(
            [
                "Name" => $name
            ]
        );

        if($ban){
            $ban->setBanned(0);
            $em = $this->getDoctrine()->getManager();
            $em->persist($ban);
            $em->flush();

            $this->addFlash("success", $name." was successfully unbanned");
        } else {
            $this->addFlash("error", "This player could not be found");
        }

        return $this->redirectToRoute("ban.index");
    }
}

templates/ban/ban.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bans{% endblock %}

{% block body %}
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Ban</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ path('home.index') }}">Home</a></li>
                            <li class="breadcrumb-item">Bans</li>
                            <li class="breadcrumb-item active">Ban</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        {% include 'messages.html.twig' %}

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <!-- /.card-header -->
                        <div class="card-body">
                            {{ form(form) }}
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
{% endblock %}

templates/ban/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bans{% endblock %}

{% block body %}
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Bans</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ path('home.index') }}">Home</a></li>
                            <li class="breadcrumb-item active">Bans</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        {% include 'messages.html.twig' %}

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <a class="btn btn-danger btn-sm" href="{{ path('ban.ban') }}">
                                <i class="fas fa-ban">
                                </i>
                                Ban
                            </a>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>{{ 'player'|trans }}</th>
                                    <th>{{ 'reason'|trans }}</th>
                                    <th>{{ 'banned_to'|trans }}</th>
                                    <th>{{ 'punisher'|trans }}</th>
                                    <th>{{ 'action'|trans }}</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for ban in bans %}
                                    <tr>
                                        <td><a href="{{ path('profile.user', {'user': ban.name}) }}">{{ ban.name}}</a></td>
                                        <td>{{ ban.reason }}</td>
                                        <td>{{ ban.formattedend|format_datetime(locale="de") }}</td>
                                        <td><a href="{{ path('profile.user', {'user': ban.teamUUID}) }}">{{ ban.teamUUID}}</a></td>
                                        <td><a class="btn btn-danger btn-sm" href="{{ path('ban.unban', {'name': ban.name}) }}">
                                                <i class="fas fa-trash">
                                                </i>
                                                Delete
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>{{ 'player'|trans }}</th>
                                    <th>{{ 'reason'|trans }}</th>
                                    <th>{{ 'banned_to'|trans }}</th>
                                    <th>{{ 'punisher'|trans }}</th>
                                    <th>{{ 'action'|trans }}</th>
                                </tr>
                                </tfoot>
                            </table>
                            <div class="navigation">
                                {{ knp_pagination_render(bans) }}
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
{% endblock %}