src/Entity/Bans.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="BansRepository")
 */
class Bans
{

    /**
     * @ORM\Id
     * @ORM\Column(type="string", length=255)
     */
    private $UUID;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="integer")
     */
    private $Banned;

    /**
     * @ORM\Column(type="integer")
     */
    private $Muted;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Reason;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $End;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Teamuuid;

    /**
     * @ORM\Column(type="integer")
     */
    private $Bans;

    /**
     * @ORM\Column(type="integer")
     */
    private $Mutes;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Firstlogin;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Lastlogin;

    /**
     * @ORM\Column(type="integer")
     */
    private $OnlineStatus;

    /**
     * @ORM\Column(type="integer")
     */
    private $OnlineTime;

    public function getUUID(): ?string
    {
        return $this->UUID;
    }

    public function setUUID(string $UUID): self
    {
        $this->UUID = $UUID;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getBanned(): ?int
    {
        return $this->Banned;
    }

    public function setBanned(int $Banned): self
    {
        $this->Banned = $Banned;

        return $this;
    }

    public function getMuted(): ?int
    {
        return $this->Muted;
    }

    public function setMuted(int $Muted): self
    {
        $this->Muted = $Muted;

        return $this;
    }

    public function getReason(): ?string
    {
        return $this->Reason;
    }

    public function setReason(string $Reason): self
    {
        $this->Reason = $Reason;

        return $this;
    }

    public function getEnd(): ?string
    {
        return $this->End;
    }

    public function setEnd(int $End): self
    {
        $this->End = $End;

        return $this;
    }

    public function getTeamUUID(): ?string
    {
        return $this->Teamuuid;
    }

    public function setTeamUUID(string $TeamUUID): self
    {
        $this->Teamuuid = $TeamUUID;

        return $this;
    }

    public function getBans(): ?int
    {
        return $this->Bans;
    }

    public function setBans(int $Bans): self
    {
        $this->Bans = $Bans;

        return $this;
    }

    public function getMutes(): ?int
    {
        return $this->Mutes;
    }

    public function setMutes(int $Mutes): self
    {
        $this->Mutes = $Mutes;

        return $this;
    }

    public function getFirstlogin(): ?string
    {
        return $this->Firstlogin;
    }

    public function setFirstlogin(string $Firstlogin): self
    {
        $this->Firstlogin = $Firstlogin;

        return $this;
    }

    public function getLastlogin(): ?string
    {
        return $this->Lastlogin;
    }

    public function setLastlogin(string $Lastlogin): self
    {
        $this->Lastlogin = $Lastlogin;

        return $this;
    }

    public function getOnlinestatus(): ?int
    {
        return $this->OnlineStatus;
    }

    public function setOnlinestatus(int $Onlinestatus): self
    {
        $this->OnlineStatus = $Onlinestatus;

        return $this;
    }

    public function getOnlinetime(): ?int
    {
        return $this->OnlineTime;
    }

    public function setOnlinetime(int $Onlinetime): self
    {
        $this->OnlineTime = $Onlinetime;

        return $this;
    }

    public function getFormattedEnd(){
        if($this->End != null && $this->End != "null"){
            $phpTimestamp = round($this->End / 1000);
            return $phpTimestamp;
        }
    }
}

src/Entity/Unbans.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UnbansRepository")
 */
class Unbans
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $uuid;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Fair;

    /**
     * @ORM\Column(type="string", length=10000)
     */
    private $Message;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Date;

    /**
     * @ORM\Column(type="integer")
     */
    private $Status;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUuid(): ?string
    {
        return $this->uuid;
    }

    public function setUuid(string $uuid): self
    {
        $this->uuid = $uuid;

        return $this;
    }

    public function getFair(): ?bool
    {
        return $this->Fair;
    }

    public function setFair(bool $Fair): self
    {
        $this->Fair = $Fair;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->Message;
    }

    public function setMessage(string $Message): self
    {
        $this->Message = $Message;

        return $this;
    }

    public function getDate(): ?string
    {
        return $this->Date;
    }

    public function setDate(string $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->Status;
    }

    public function setStatus(int $Status): self
    {
        $this->Status = $Status;

        return $this;
    }
}

src/Controller/Api/UnbansController.php
<?php

namespace App\Controller\Api;

use App\Repository\BansRepository;
use App\Repository\TokensRepository;
use App\Repository\UnbansRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class UnbansController extends AbstractController{

    private $tokensRepository;
    private $unbansRepository;
    private $bansRepository;

    public function __construct(TokensRepository $tokensRepository, UnbansRepository $unbansRepository, BansRepository $bansRepository)
    {
        $this->tokensRepository = $tokensRepository;
        $this->unbansRepository = $unbansRepository;
        $this->bansRepository = $bansRepository;
    }

    /**
     * @Route("/api/unbans", name="api.unbans", methods={"POST"})
     */
    public function index(Request $request){
        $request = json_decode($request->getContent());
        $token = $this->tokensRepository->findOneBy(['token' => (array_key_exists("token", $request)) ? $request->token : null]);
        if(!$token){
            return $this->json([
                'error' => 'Not permitted'
            ], 401);
        }

        if(!array_key_exists("unban", $request) || !array_key_exists("status", $request)){
            $openUnbans = $this->unbansRepository->findBy(['Status' => 0]);
            $closedUnbans = $this->unbansRepository->findBy(['Status' => [1, 2, 3]]);

            foreach ($openUnbans as $unban){
                $uuid = $this->bansRepository->findOneBy(['UUID' => $unban->getUUID()]);

                $unban->setUuid($uuid->getName());
            }

            foreach ($closedUnbans as $unban){
                $uuid = $this->bansRepository->findOneBy(['UUID' => $unban->getUUID()]);

                $unban->setUuid($uuid->getName());
            }

            return $this->json([
                'unbans' => [
                    'open' => $openUnbans,
                    'closed' => $closedUnbans
                ]
            ]);
        }

        if($request->status == "2"){
            if(!array_key_exists("date", $request)){
                return $this->json([
                    'error' => 'Invalid request'
                ], 400);
            }
        }

        $unban = $this->unbansRepository->findOneBy(['id' => $request->unban]);
        if($unban){
            $unban->setStatus((int)$request->status);
            $ban = $this->bansRepository->findOneBy(['UUID' => $unban->getUuid()]);

            switch ($request->status){
                case "1":
                    $ban->setBanned(0);
                    break;
                case "2":
                    $date = new \DateTime($request->date);
                    $timestamp = $date->getTimestamp();
                    $timestamp = $timestamp * 1000;
                    $ban->setEnd($timestamp);
                    break;
            }

            $em = $this->getDoctrine()->getManager();
            $em->flush();

            return $this->json([
                'success' => 'Unban request was updated'
            ]);
        } else {
            return $this->json([
                'error' => 'Unban request not found'
            ], 404);
        }
    }

}

src/Controller/UnbanController.php
<?php

namespace App\Controller;

use App\Form\UnbanrequestType;
use App\Repository\BansRepository;
use App\Repository\UnbansRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Dotenv\Dotenv;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * @Route("/unbans", name="unban.")
 */
class UnbanController extends AbstractController
{

    private $unbansRepository;
    private $bansRepository;
    private $translator;

    public function __construct(UnbansRepository $unbansRepository, BansRepository $bansRepository, TranslatorInterface $translator)
    {
        $this->unbansRepository = $unbansRepository;
        $this->bansRepository = $bansRepository;
        $this->translator = $translator;
    }

    /**
     * @Route("/", name="index")
     */
    public function index()
    {
        $unbans = $this->unbansRepository->findBy(['Status' => 0]);

        foreach ($unbans as $unban){
            $playerUuid = $this->bansRepository->findOneBy(['UUID' => $unban->getUuid()]);

            $unban->setDate($unban->getDate());
            $unban->setUuid($playerUuid->getName());
        }

        return $this->render('unban/index.html.twig', [
            'unbans' => $unbans,
        ]);
    }

    /**
     * @Route("/archive", name="archive")
     */
    public function archive()
    {
        $unbans = $this->unbansRepository->findBy(['Status' => [1, 2, 3]]);

        foreach ($unbans as $unban){
            $playerUuid = $this->bansRepository->findOneBy(['UUID' => $unban->getUuid()]);

            $unban->setDate($unban->getDate());
            $unban->setUuid($playerUuid->getName());
        }

        return $this->render('unban/archive.html.twig', [
            'unbans' => $unbans,
        ]);
    }

    /**
     * @Route("/view/{id}", name="view")
     */
    public function view($id, Request $request){
        $unban = $this->unbansRepository->findOneBy(['id' => $id]);
        $playerUuid = $this->bansRepository->findOneBy(['UUID' => $unban->getUuid()]);

        $unban->setUuid($playerUuid->getName());
        $unban->setDate($unban->getDate());

        $oldEnd = $playerUuid->getEnd();
        $playerUuid->setEnd(round($playerUuid->getEnd()/1000));

        $form = $this->createForm(UnbanrequestType::class);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $status = $form->get('status')->getData();
            $unban->setStatus($status);
            $unban->setUuid($playerUuid->getUUID());
            $em = $this->getDoctrine()->getManager();
            switch ($status){
                case 1:
                    $playerUuid->setBanned(0);

                    $em->flush();
                    break;
                case 2:
                    $newEnd = $form->get('endpicker')->getData();
                    $now = new \DateTime();

                    if($newEnd > $now){
                        $unban->setUuid($playerUuid->getUUID());
                        $playerUuid->setEnd(round($newEnd->getTimestamp() * 1000));

                        $em->flush();

                        return $this->redirectToRoute('unban.index');
                    } else {
                        $this->addFlash('error', $this->translator->trans('date_past'));
                    }
                    break;
                case 3:
                    $playerUuid->setEnd($oldEnd);
                    $em->flush();
                    break;
            }
            return $this->redirectToRoute('unban.index');
        }

        return $this->render('unban/view.html.twig', [
            'unban' => $unban,
            'form' => $form->createView(),
            'player' => $playerUuid
        ]);
    }

    /**
     * @Route("/request", name="request")
     */
    public function requestUnban()
    {
        return $this->render('unban/index.html.twig', [
            'controller_name' => 'UnbanController',
        ]);
    }
}

templates/unban/archive.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'nav_unbanrequests'|trans }}{% endblock %}

{% block body %}
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>{{ 'nav_unbanrequests'|trans }}</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ path('home.index') }}">Home</a></li>
                            <li class="breadcrumb-item active">{{ 'nav_unbanrequests'|trans }}</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        {% include 'messages.html.twig' %}

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <a class="btn btn-success btn-sm" href="{{ path('unban.index') }}">
                                <i class="fas fa-inbox"></i>
                                {{ 'all_unbans'|trans }}
                            </a>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>{{ 'player'|trans }}</th>
                                    <th>{{ 'date'|trans }}</th>
                                    <th>{{ 'action'|trans }}</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for unban in unbans %}
                                    <tr>
                                        <td>{{ unban.uuid}}</td>
                                        <td>{{ unban.date|format_datetime(locale="de") }}</td>
                                        <td><a class="btn btn-secondary btn-sm" href="{{ path('unban.view', {'id': unban.id}) }}">
                                                <i class="fas fa-eye"></i>
                                                {{ 'view'|trans }}
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>{{ 'player'|trans }}</th>
                                    <th>{{ 'date'|trans }}</th>
                                    <th>{{ 'action'|trans }}</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
{% endblock %}

templates/unban/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'nav_unbanrequests'|trans }}{% endblock %}

{% block body %}
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>{{ 'nav_unbanrequests'|trans }}</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ path('home.index') }}">Home</a></li>
                            <li class="breadcrumb-item active">{{ 'nav_unbanrequests'|trans }}</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        {% include 'messages.html.twig' %}

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <a class="btn btn-secondary btn-sm" href="{{ path('unban.archive') }}">
                                <i class="fas fa-archive"></i>
                                Archive
                            </a>
                            <a class="btn btn-secondary btn-sm" href="{{ path('userunban.create') }}">
                                <i class="fas fa-file-alt"></i>
                                {{ 'unbans_page'|trans }}
                            </a>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>{{ 'player'|trans }}</th>
                                    <th>{{ 'date'|trans }}</th>
                                    <th>{{ 'action'|trans }}</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for unban in unbans %}
                                    <tr>
                                        <td>{{ unban.uuid}}</td>
                                        <td>{{ unban.date|format_datetime(locale="de") }}</td>
                                        <td><a class="btn btn-secondary btn-sm" href="{{ path('unban.view', {'id': unban.id}) }}">
                                                <i class="fas fa-eye"></i>
                                                {{ 'view'|trans }}
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>{{ 'player'|trans }}</th>
                                    <th>{{ 'date'|trans }}</th>
                                    <th>{{ 'action'|trans }}</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
{% endblock %}

templates/unban/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'nav_unbanrequests'|trans }}{% endblock %}

{% block body %}
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>{{ 'nav_unbanrequests'|trans }}</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ path('home.index') }}">Home</a></li>
                            <li class="breadcrumb-item active">{{ 'nav_unbanrequests'|trans }}</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        {% include 'messages.html.twig' %}

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <!-- /.card-header -->
                        <div class="card-body">
                            <h3>{{ 'player'|trans }}</h3>
                            <a href="{{ path('profile.user', {'user': unban.uuid}) }}">{{ unban.uuid }}</a><br>
                            <br>
                            <h3>{{ 'fair_question'|trans }}</h3>
                            <p>
                                {% if unban.fair == 1 %}
                                    {{ 'fair_answer_1'|trans }}
                                {% else %}
                                    {{ 'fair_answer_0'|trans }}
                                {% endif %}
                            </p>
                            <br>
                            <h3>{{ 'message'|trans }}</h3>
                            <p>{{ unban.message }}</p>
                            <br>
                            <h3>{{ 'unban_date'|trans }}</h3>
                            <p>{{ unban.date|format_datetime(locale="de") }}</p>
                            {% if unban.status == 0 %}
                            <br>
                            <h3>{{ 'ban_end'|trans }}</h3>
                            <p>{{ player.end|format_datetime(locale="de") }}</p>
                            <br>
                            {{ form_start(form) }}
                            <div id="datepicker" style="display: none">
                                <h3>{{ 'datepicker'|trans }}</h3>
                                <br>
                                <div class="container">
                                    <p>{{ 'date'|trans }}</p>
                                    <div class="row">
                                        <div class="col-md-4">
                                            {{ form_widget(form.endpicker.date.day, {'attr': {'class': 'form-control'}}) }}
                                        </div>
                                        <div class="col-md-4">
                                            {{ form_widget(form.endpicker.date.month, {'attr': {'class': 'form-control'}}) }}
                                        </div>
                                        <div class="col-md-4">
                                            {{ form_widget(form.endpicker.date.year, {'attr': {'class': 'form-control'}}) }}
                                        </div>
                                    </div>
                                </div>
                                <br>
                                <div class="container">
                                    <p>{{ 'time'|trans }}</p>
                                    <div class="row">
                                        <div class="col-md-4">
                                            {{ form_widget(form.endpicker.time.hour, {'attr': {'class': 'form-control'}}) }}
                                        </div>
                                        <div class="col-md-8">
                                            {{ form_widget(form.endpicker.time.minute, {'attr': {'class': 'form-control'}}) }}
                                        </div>

                                    </div>
                                </div>
                            </div>
                            <br>
                            {{ form_widget(form.status) }}
                            <br>
                            {{ form_widget(form.submit) }}
                            {{ form_end(form) }}
                            {% else %}
                                <div class="p-2">
                                    <div class="alert alert-success p">
                                        <h4><i class="icon fa fa-check"></i> {{ 'success'|trans }}</h4>
                                        {{ 'already_finished'|trans }}
                                    </div>
                                </div>
                            {% endif %}
                            <script>
                                function toggleDateField() {
                                    var datepicker = document.getElementById('datepicker');
                                    var choice = document.getElementById('unbanrequest_status');

                                    if(choice.selectedIndex == 1){
                                        datepicker.style.display = "block";
                                    } else {
                                        datepicker.style.display = "none";
                                    }
                                }
                            </script>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
{% endblock %}